### ISSUE TITLE
First iOS 11 "malware"???

### ISSUE THREAD

**Issue by docaiden** [GeopJr/block-revokes-async_wake#1]
This can cause harm to devices. Blocking OCSP.apple.com will block all new apps from being sideloaded. If this isnt reversed by the time the device's current apps expire, they will not be able to sideload again, and if they want to sideload, their only choice is to go to 11.2.

**Comment by haydarai** [comment]
What do you mean by device's current apps expire and will not be able to sideload again?

**Comment by GeopJr** [comment]
Closing. There's a disclaimer. Async_wake wasn't meant to be used by normal users. This IPA is just a way to block ocsp.apple.com with one tap. There's no need to even use this IPA since you can change the hosts file yourself with filza. 

HOW TO REMOVE IT: install filzajailed , navigate to /etc/ , open the file name "hosts" with a text editor , remove the line containing ocsp.apple.com

PS. I can still sideload apps and I always could when I was using it on 10.2
