### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by AFishNamedFish** [GeopJr/block-revokes-async_wake#2]
Hello, I was hoping that this program would allow me to use my original sideloaded apps after 7 days when they expire.

I followed the install instructions but the async_wake_ios app is not doing anything. The app disappears as soon as it is launched.

I am running iOS 11.3 on an iPad Mini. Any help is appreciated!

**Comment by GeopJr** [comment]
1) it works for enterprise apps
2) it uses async_awake-fun which if you didnt know works only for iOS <=11.1.2 
3) there's no need for this ipa since iOS <= 11.1.2 is jailbroken with electra
4) this was made when there was not a jailbreak
5) iOS 11.3 doesnt have a jailbreak yet
6) check r/jailbreak on reddit for news about jailbreaking

**Comment by AFishNamedFish** [comment]
Thank you for the info.
